global:
  scrape_interval: 5s

rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: 'camrail_api'
    static_configs:
      # API dans Docker - même réseau que Prometheus
      - targets: ['api:5000']
